# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/gdubicki/pre-commit-pngquant
    rev: 777d63c
    hooks:
      - id: pngquant
