# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/gdubicki/pre-commit-pngquant
    rev: 9fad42f9df2ec8306c73d3e7c0628893ead0ebeb
    hooks:
      - id: pngquant
        args: [--speed=1]
