---
name: Publish to GitHub

on:
  push:
    tags:
      - 'v*'

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
          check-latest: true
      - name: Build
        run: |
          ./build.sh
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          # This token is provided by Actions, you do not need to create your own token
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          prerelease: true
          files: |
            dynamotd-*
