---
name: Tests

on:
  push:

jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true
      - name: Test
        run: |
          go test -v tests/*
